---
title: "Trazas"
output: html_document
---

```{r}
set.seed(2020)
(points <- as_tibble(t(replicate(15, sample(1:10, 2)))) %>% rename(x = V1, y = V2) %>% bind_rows(tibble(x = 0, y = 0)))
```

```{r}
ggplot(points, aes(x, y)) + geom_point()
```


```{r}
desired_length <- 13 # or whatever length you want
results <- vector(mode = "list", length = desired_length)
for(i in 1:length(results)) {
  out_rkmeans <- rkmeans(x = points, centers = 2, iter.max = 5, nstart = 1, trace = FALSE, distances = 1:13, dist = i) 
  results[[i]] <- out_rkmeans
}
```

```{r}
total_errors <- lapply(results, function(x) x$tot.withinss)
total_errors <- lapply(total_errors, function(x) data.frame(t(x)))
total_errors <- Reduce(bind_rows, total_errors)
```

```{r}
set.seed(2020)
out_rkmeans1 <- rkmeans(x = points, centers = 2, iter.max = 5, nstart = 1, trace = FALSE, distances = 1:13, dist = 6) 
out_rkmeans1$cluster
out_rkmeans1$withinss
```

```{r}
set.seed(2020)
out_rkmeans2 <- rkmeans(x = points, centers = 2, iter.max = 5, nstart = 1, trace = FALSE, distances = 1:13, dist = 2) 
out_rkmeans2$cluster
out_rkmeans2$withinss
```

