---
title: "Clustering con distintas distancias"
output: html_notebook
---

# Los datos

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(clusterlab)
#library(devtools)
#install_github("noeliarico/consensus/consensus")
library(consensus)
```


```{r message=FALSE}
data <- clusterlab(centers = 3, # the number of clusters to simulate 
                   # the number of units of the radius of the circle on which the clusters are generated
                   r = 2, 
                   # the number of samples in each cluster
                   numbervec = c(4, 4, 4),
                   # standard deviation of each cluster
                   sdvec = c(1, 3, 2),
                   # how many units to push each cluster away from the initial placement
                   alphas = c(3, 5, 1),
                   # the number of features for the data
                   features = 2,
                   seed = 1234
                   
                   )
```

Los datos generados aleatoriamente son los siguientes:

```{r}
(points <- as.tibble(t(data$synthetic_data)) %>% rename(x = 1, y = 2))
```

```{r}
# Clean the object so it has a good format
clusters <- data$identity_matrix %>% pull(cluster)
data <- points %>% mutate(cluster = clusters) 
``` 

Claramente, los clusters que se generan son:

```{r}
plot_real_clusters(data, "cluster", "x", "y")
```

```{r}
kmeansM2 <- kmeans(data, centers = 3, nstart = 10)
```

```{r}
kmeansM2$iter
```

<!-- 
Voy a mirar la distancia de c1s1 al resto de puntos. Esa distancia la voy a calcular utilizando 5 valores de minkowski diferentes

```{r}
for(thep in 1:5) {
  distp <- as.matrix(dist(points, method = "minkowski", p = thep))[-1, 1]
  print("---------------------------------------------------------------------")
  print(distp)
}
```
-->
